config/routes.rb
Rails.application.routes.draw do

  mount Payola::Engine => '/payola', as: :payola
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'hats#index'

  get 'users/new' => 'users#new', as: :sign_up
  post '/users' => 'users#create', as: :users

  get 'sign_in' => 'sessions#new', as: :sign_in
  post 'sign_in' => 'sessions#create'
  delete 'sign_out' => 'sessions#delete', as: :sign_out

  get 'cart' => 'carts#show', as: :shopping_cart
  post 'carts/add/:hat_id' => 'carts#add', as: :add_to_cart
  delete 'carts/remove/:hat_id' => 'carts#remove', as: :remove_from_cart
  get 'receipt/:sale_guid' => 'carts#receipt', as: :receipt
end

app/models/cart.rb
class Cart < ActiveRecord::Base

  belongs_to :user
  has_many :cart_items
  include Payola::Sellable

  def price_in_dollars
    self.price.to_i / 100.0
  end

  def redirect_path(payola_sale)
    "/receipt/#{payola_sale.guid}"
  end
end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base

  belongs_to :cart
  belongs_to :hat

  def price=(dollars)
    self.price_in_cents = dollars.to_f * 100
  end

  def price
    self.price_in_cents.to_i / 100.0
  end
  
end

app/models/hat.rb
class Hat < ActiveRecord::Base

  attachment :hat_image
  # validates :name, :photo, :description, :price_in_cents

  def price=(dollars)
    self.price_in_cents = dollars.to_f * 100
  end

  def price
    self.price_in_cents.to_i / 100.0
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password
  has_many :carts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action do
    @current_user = User.find_by id: session[:user_id]
  end

  def authenticate_user!
    if @current_user.blank?
      redirect_to sign_in_path
    end
  end

  # def sign_in(user)
  #   session[:user_id] = @user.id
  # end

  def sign_out
    session.delete :user_id
  end

end

app/controllers/carts_controller.rb
require 'securerandom'
class CartsController < ApplicationController


  before_action :authenticate_user!

  before_action do
    @cart = @current_user.carts.find_by completed: false
    if @cart.blank?
      @cart = Cart.new
      @cart.user = @current_user
      @cart.name = [@current_user.username, SecureRandom.hex].join("-")
      @cart.permalink = SecureRandom.hex
      @cart.price = 0
      @cart.save
    end
  end

  def receipt

    @sale = Payola::Sale.find_by guid: params[:sale_guid]
    @cart = @sale.product
  end

  def add
    #identify the hat to be added to cart
    @hat = Hat.find params[:hat_id]
    #sets the hat to cart_item
    cart_item = @cart.cart_items.find_by hat_id: @hat.id

    if cart_item.present?
      #if the hat is already present in the cart, increase quantity by 1
      cart_item.quantity += 1
      cart_item.save
    else
      #creates new CartItem with given attributes
      CartItem.create cart: @cart, hat: @hat, price: @hat.price
    end
    @cart.price = @cart.cart_items.map{|cart_item| cart_item.price_in_cents * cart_item.quantity}.sum
    @cart.save
    redirect_to shopping_cart_path
  end

  def remove
    @hat = Hat.find params[:hat_id]

    cart_item = @cart.cart_items.find_by(hat_id: @hat.id)
    cart_item.destroy
    @cart.price = @cart.cart_items.map{|cart_item| cart_item.price_in_cents * cart_item.quantity}.sum
    @cart.save
    redirect_to shopping_cart_path
  end

  def show
  end
end

app/controllers/hats_controller.rb
class HatsController < ApplicationController

  before_action :authenticate_user!


  def index
    @hats = Hat.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    username = params[:username]
    password = params[:password]
    password_confirm = params[:password_confirmation]

    user = User.find_by username: username
    if user && user.authenticate(password)
      session[:user_id] = user.id
      redirect_to root_path, notice: "You have logged in!"
    else
      flash.now[:alert] = "Username and Password do not match"
      render :new
    end
  end

  def delete
    sign_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new params.require(:user).permit(:username, :email, :password, :password_confirmation)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Welcome to Cat Hats!"
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/hats_helper.rb
module HatsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/receipt.html.erb
<% content_for(:page_title) do %>
  Order Receipt | 
<% end %>

<h2>Thanks for your business.</h2>
<p>
  A confirmation email would be sent shortly, but our highly skilled dev team is sleepy.
</p>

<table class="table">
  <thead>
    <tr>
      <th>Item</th>
      <th>Quantity</th>
      <th>Price</th>
    </tr>
  </thead>
  <tbody>
    <% @cart.cart_items.each do |cart_item| %>
      <tr>
        <td><%= cart_item.hat.name %></td>
        <td><%= cart_item.quantity %></td>
        <td><%= number_to_currency cart_item.price %></td>
      </tr>
    <% end %>
    <tr>
      <td></td>
      <td><strong>Total:</strong></td>
      <td><%= number_to_currency @cart.price_in_dollars %></td>
    </tr>
  </tbody>
</table>

app/views/carts/show.html.erb
<% content_for(:page_title) do %>
  Your Cart | 
<% end %>

<table class="table">
  <thead>
    <tr>
      <th>Item</th>
      <th>Quantity</th>
      <th>Price</th>
      <th>Remove</th>
    </tr>
  </thead>
  <tbody>
    <% @cart.cart_items.each do |cart_item| %>
      <tr>
        <td><%= cart_item.hat.name %></td>
        <td><%= cart_item.quantity %></td>
        <td><%= number_to_currency cart_item.price %></td>
        <td><%= link_to "Remove", remove_from_cart_path(hat_id: cart_item.hat.id), method: :delete, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
    <tr>
      <td></td>
      <td></td>
      <td><strong>Total:</strong></td>
      <td><%= number_to_currency @cart.price_in_dollars %></td>
    </tr>
  </tbody>
</table>
<% if @cart.cart_items.any? %>
  <%= render 'payola/transactions/checkout', sellable: @cart, button_text: "Order Hats!", name: "Cat Hats!" %>
<% end %>

app/views/hats/index.html.erb
<% @hats.each do |hat| %>
  <div class="hat">
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <%= image_tag hat.photo %>
        <div class="caption">
          <h3><%= hat.name %></h3>
          <p><%= hat.description %></p>
          <p><%= number_to_currency hat.price %></p>
          <%= link_to "Add to Cart", add_to_cart_path(hat_id: hat.id), method: :post, class: "btn btn-default btn-block" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for :page_title %>CatHats!</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <nav class="page-header">
        <h1><%= link_to "Cat Hats!", root_path %><small> Unrequited love is a terrible thing to waste</small></h1>
        <ul class="nav navbar-nav navbar-right">
          <% if @current_user %>
          <li>
            <h4><%= link_to "Log Out", sign_out_path, method: :delete %></h4>
          </li>
          <% else %>
          <li>
            <%= link_to "Sign-In", sign_in_path %>
          </li>
          <% end %>
        </ul>
    </nav>

    <%= yield %>
  </div>

</body>
</html>

app/views/users/new.html.erb
<% content_for(:page_title) do %>
  Create Account | 
<% end %>

<div class="col-md-6 col-md-offset-3">
  <h1>Please sign up</h1>

  <%= simple_form_for @user do |f| %>
    <%= f.input :username %>
    <%= f.input :email %>
    <%= f.input :password %>
    <%= f.input :password_confirmation, label: "Confirm Password" %>
    <%= f.submit "Sign Up", class: "btn btn-success btn-lg btn-block" %>

  <% end %>
</div>